[project]
name = "wods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.0",
    "pandas>=1.3.0",
    "plotly>=5.0.0",
    "requests>=2.25.0",
    "streamlit>=1.28.0",
]
